### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ppodds** [ppodds/relno-action#17]
# Roadmap

Check [this branch](https://github.com/ppodds/release-note/tree/dev/v1.0.0) for the current developing progress.

## Features

The features below will be added in the next major release.

- [x] Plugin system
- [ ] Fully configurable commit message parser
- [x] TypeScript config file
- [x] Tag Syntax improve
